// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 1);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1698528943);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1698529063);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1698528945);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1698529066);
user_pref("browser.search.region", "FR");
user_pref("calendar.caldav.googleResync", 1698529065);
user_pref("calendar.list.sortOrder", "e7044e6c-f40a-4bbe-b3e0-a9109cb3c863");
user_pref("calendar.registry.e7044e6c-f40a-4bbe-b3e0-a9109cb3c863.calendar-main-default", true);
user_pref("calendar.registry.e7044e6c-f40a-4bbe-b3e0-a9109cb3c863.calendar-main-in-composite", true);
user_pref("calendar.registry.e7044e6c-f40a-4bbe-b3e0-a9109cb3c863.disabled", true);
user_pref("calendar.registry.e7044e6c-f40a-4bbe-b3e0-a9109cb3c863.name", "Home");
user_pref("calendar.registry.e7044e6c-f40a-4bbe-b3e0-a9109cb3c863.type", "storage");
user_pref("calendar.registry.e7044e6c-f40a-4bbe-b3e0-a9109cb3c863.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Paris");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1698528955111");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1698528117);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230704155023");
user_pref("extensions.lastAppVersion", "102.13.0");
user_pref("extensions.lastPlatformVersion", "102.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"d4a0c536-f552-4ae5-8606-51e7e077cef5\",\"google@search.mozilla.org\":\"8bcf2ca5-1bc4-4aa3-ad3f-e4b792f1688c\",\"ddg@search.mozilla.org\":\"0f5b1898-0986-4dad-857b-21bc4ad5dd2a\",\"amazon@search.mozilla.org\":\"6516e539-8d20-4227-a63f-3d6187e1761f\",\"chambers-en-GB@search.mozilla.org\":\"2fd760bd-2fda-45a4-897a-c043f32b6da3\",\"wikipedia@search.mozilla.org\":\"644970b2-af0a-4ea7-8692-82931b2f873e\",\"bing@search.mozilla.org\":\"78e670d9-dba7-4cb9-a087-4888e00262c4\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1698528942);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "157071ca-b3b4-47f6-939b-193135765ec");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.13.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1698528945);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -27);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1698529090);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1698529090);
user_pref("services.settings.thunderbird.search-config.last_check", 1698529090);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1698529090);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1698528943);
user_pref("toolkit.telemetry.cachedClientID", "12a11cbe-b784-458c-968c-81353b8c7ba8");
user_pref("toolkit.telemetry.previousBuildID", "20230704155023");
